import { Inter, Josefin_Sans } from 'next/font/google';
import StyledComponentsRegistry from '../libs/registry';

const inter = Inter({ subsets: ['latin'] });
const josefinSans = Josefin_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
